### ISSUE TITLE
Suggest a FAQ

### ISSUE THREAD

**Issue by richelbilderbeek** [jordansissel/xdotool#116]
Thanks for the awesome `xdotool`!

I would have liked to do a Pull Request with a question and recently found solution, but there is no `FAQ.md` file. I wish there was, as I think it's better than having all these answers all around the internet.

Would you like to allow for that infrastructure? A 'no' is perfectly fine.

**Comment by jordansissel** [comment]
Lovely idea :)

Github supports wikis, so we have an option to do a wiki instead of a FAQ.md, but I am open to either. We can start with a FAQ.md first and grow from there. +1

**Comment by richelbilderbeek** [comment]
Has been done, thanks for accepting!
