### ISSUE TITLE
getmouselocation doesn't modify window stack, why not?

### ISSUE THREAD

**Issue by alaricljs** [jordansissel/xdotool#118]
I have a macro and I am trying to work around a Java bug with 'focus follows mouse'  Basically The focus doesn't _always_ follow the mouse.  For the macro to work I am expecting the output to land on the window that is under the mouse so I tried getmouselocation but it doesn't modify the window stack for some reason.  It returns the window ID, but that can't be used w/ search.  Using the window id for send doesn't work either for your own noted reasons.

Can getmouselocation be made to set the window stack?  On the other hand, why is it a random scattering of commands that can use a window id and not all of them?

**Comment by jordansissel** [comment]
Having getmouselocation set the window stack is a lovely idea!

**Comment by emanuele6** [comment]
I would like this too.

**Comment by jordansissel** [comment]
Following up  -- I ran into this today. For a workaround, I'm doing this until we have this command modify the windowstack:

```
eval "$(xdotool getmouselocation --shell)"

xdotool windowactivate $WINDOW
```

**Comment by jordansissel** [comment]
https://github.com/jordansissel/xdotool/pull/322 addresses this.
