### ISSUE TITLE
xdotool type doesn't include spaces when pulling a string from a file

### ISSUE THREAD

**Issue by Yokai-Seishinkage** [jordansissel/xdotool#119]
file.txt has a single line. The line is: "Hello all. How are you doing?"

Using the command "shuf -n 1 file.txt" as a variable to pull the line from file.txt into xdotool to type.

GEN="$(shuf -n 1 file.txt)"
xdotool type $GEN

Output is: "Helloall.Howareyoudoing?"

xdotool does not recognize spaces in strings unless typing direct input with single quotes. Such as:

xdotool type 'Hello all. How are you doing?"

Output is: "Hello all. How are you doing?"

**Comment by jordansissel** [comment]
This is one of those weird times when the shell is doing something you might not expect.

If you have this:

```
foo="hello world"
```

and you invoke `xdotool type $foo`, then it is the same as if you had done `xdotool type hello world` (no quotes).

You can solve this by using doublequotes around your variable:

```
# Solution
xdotool type "$GEN"
```

**Comment by Yokai-Seishinkage** [comment]
I have attempted to use $GEN, '$GEN' and "$GEN" and in both single and double quotes, when the variable is calling a string from a file, the command xdotool prints $GEN but not what $GEN does.

#!/bin/bash
clear

main() {
GEN="$(shuf -n 1 file.txt)"
xdotool type "$GEN"
exit 0
}

main

This script prints out "$GEN" instead of a line from file.txt. I have spent the past week, hours each day, trying to figure out why this is happening and it isn't simply the issue of the single or double quotes. Having no quotes is the only way any file content is printed. But, spaces are ignored.

**Comment by Yokai-Seishinkage** [comment]
I actually tried the "$GEN" in the same script that was giving me issues after a fresh install on a more powerful laptop. For some reason in double quotes it works as it should on the better laptop. I have deduced that it is an issue with the outdated machine and not xdotool itself.

**Comment by zguellit** [comment]
the double quotes solved the problem for me thanks
