### ISSUE TITLE
Cancellable selectwindow

### ISSUE THREAD

**Issue by wavexx** [jordansissel/xdotool#136]
In a script I wrote, I'm using `selectwindow` to let the user select the window to operate on.
However, I'd like the user to be able to cancel the action in some way or another.

There seems no way to do that from the user's perspective. Any button press will return from `windowselect`. I would have expected that only button1 works, with other buttons canceling the action instead.

Just to follow an example from the manpage, `xdotool selectwindow windowkill` is not abortable unless by killing xdotool itself.

**Comment by jordansissel** [comment]
I agree with your proposal to make anything other than button1 cancel the
selection

**Comment by jordansissel** [comment]
I think https://github.com/jordansissel/xdotool/pull/137 should fix it, but I haven't tested yet (I don't have any machines with X11 right now). Are you able to test this?

**Comment by wavexx** [comment]
Works as intended! Thanks.
