### ISSUE TITLE
alt-a does not work since upgrade to Ubuntu 16.04

### ISSUE THREAD

**Issue by robin13** [jordansissel/xdotool#153]
I recently upgraded from Ubuntu 14.04 -> 16.04, and since then my xdotool keyboard shortcut to mute/unmute the Zoom application does not work...

The command I use is:

```
xdotool search --name "Zoom Meeting ID" windowactivate --sync key --clearmodifiers alt+a
```

It does make the window active, but the application does not receive the alt+a command.  If I manually do alt+a, the desired mute occurs.
Any ideas if there is something wrong with the command I am using, or what might have changed from Ubuntu 14.04 -> 16.04 which would cause this to stop working?

**Comment by jordansissel** [comment]
Weird. I'll try to reproduce on Fedora 24 (not the same, but hopefully similar)

**Comment by jordansissel** [comment]
On Fedora 24, your command works. Hmm :\

**Comment by jordansissel** [comment]
Something to try; for the keybinding that you are using to run this command, can you add `sleep 0.5` before the command? like: 

```
sleep 0.5; xdotool search --name "Zoom Meeting ID" windowactivate --sync key --clearmodifiers alt+a
```

My hypothesis is that --clearmodifiers is somehow not working, though I think you said you mapped it to `Pause` which isn't normally a modifier key.

This is weird. I'll sync up with you to see what's going on. <3

**Comment by jakommo** [comment]
Thanks @jordansissel tried adding the sleep, but didn't work.

Compiled the latest version from master and now its working again.
Ubuntu 16.04 ships with version `3.20150503.1` which seems a bit outdated.

@robin13 had to install `libxtst-dev libxinerama-dev libxkbcommon-x11-dev libxkbcommon-dev libxcb-xkb-dev` to compile it.

**Comment by robin13** [comment]
Works for me - thank you! :)
