### ISSUE TITLE
Test examples in Travis CI

### ISSUE THREAD

**Issue by richelbilderbeek** [jordansissel/xdotool#168]
If you accept [my Pull Request](https://github.com/jordansissel/xdotool/pull/167), I'd love to test the examples in the `examples` folder by Travis CI. I volunteer to do so as well :-)

**Comment by lheckemann** [comment]
Since the PR is merged, suggest close?

**Comment by richelbilderbeek** [comment]
Is there a desire to test the examples in Travis CI? If yes, I still volunteer to do so, and can be assigned to do so here. If there is no such desire, one can choose to write `Won't do so` or so, and close :-)

**Comment by lheckemann** [comment]
@jordansissel ?

**Comment by jordansissel** [comment]
@lheckemann https://github.com/jordansissel/xdotool/pull/167 was merged. I may have forgotten to activate it on travis, but it is now active: https://travis-ci.org/jordansissel/xdotool

Caveat: I have never run these tests on Travis, so it's possible there are several false alarms. If things break, I would appreicate any efforts to resolve the failing tests.

**Comment by anko** [comment]
I believe there has been a misunderstanding.

#167 added only the _build_ as a Travis script: https://github.com/jordansissel/xdotool/blob/08c8e2d6cad60a69ce415499e34865157a1b66fd/.travis.yml#L15-L18

The _tests_ are currently not run.

I think is a request to *also run the tests* on Travis.

**Comment by richelbilderbeek** [comment]
Thanks @anko for voicing my idea better than I apparently could :+1:
