### ISSUE TITLE
http://www.semicomplete.com/projects/xdotool/ still recommends downloading version 2.2011*

### ISSUE THREAD

**Issue by shlomif** [jordansissel/xdotool#171]
Hi!

Thanks for xdotool! http://www.semicomplete.com/projects/xdotool/ still recommends downloading version 2.2011* whereas there's already 3.2016*.

Please update it.

**Comment by antofthy** [comment]
Ditto.  Or at least point the page to Github

**Comment by jordansissel** [comment]
Updated to point at GitHub and the xdotool releases page. <3

**Comment by shlomif** [comment]
Thanks!
