### ISSUE TITLE
Unable to find where getmouselocation is in the code

### ISSUE THREAD

**Issue by wertyy102** [jordansissel/xdotool#181]
I'm writing a script for work to call on a mac, and we cannot use xcode/hombrew to run things, as we need to be able to plug in a usb and run the tool, testing to see if the mouse works, and xdotool is the only way I have found, unless you can grep pointer location, and I need to check location and then check it again 5 seconds later to verify mouse got moved to pass the test.      the only part of xdotool i need to call is this, in order to put it into the script that is getting distributed to my colleagues.  Any help is greatly appreciated :D

**Comment by jordansissel** [comment]
Here: https://github.com/jordansissel/xdotool/blob/master/xdo.c#L872-L925

**Comment by wertyy102** [comment]
Awesome thank you so much!
