### ISSUE TITLE
xdotool not working when invoked as a keyboard shortcut

### ISSUE THREAD

**Issue by tedstoychev** [jordansissel/xdotool#210]
Under 'System Settings' > 'Keyboard' > 'Shortcuts' I have bound the command:
`xdotool key --clearmodifiers End` to:
`Ctrl+E`

But when I press the combination e.g. when I'm inside a text editor, nothing happens.

OS: Linux Mint 18
xdotool: v3.20150503.1

![screenshot](https://user-images.githubusercontent.com/1466111/39408372-ca7756a4-4bdd-11e8-9efb-c4405c9b9371.png)

**Comment by yfeleke** [comment]
+1 for redhat 7

**Comment by lj94093** [comment]
+1 for manjaro deepin

**Comment by DiagonalArg** [comment]
I am having the same problem, though in my case I am trying to define a hotkey to `xdotool key ctrl+l` or `xdotool key ctrl+shift+v`.  Both work when executed in a terminal, but fail when assigned to a hotkey.  I added the `sleep 0.100`, but that did not help.

On an unrelated issue, I will add that `xdotool key ctrl+shift+v`, when executed in a terminal, pastes the contents of the clipboard twice into the window.

**Comment by otizonaizit** [comment]
Thanks @jordansissel !!! That fixed it for me. I had the problem while trying to use xdotool in fvwm. Not sure I understand your explanation, though. In my case, I have the following in the fvwm configuration:
```
Key Left  A M Exec xdotool sleep 0.100 key Prior
Key Right A M Exec xdotool sleep 0.100 key Next
```
which is meant to remap alt+left/right to alt+prior/next (it is a workaround for a broken keyboard). 
Following your logic, what is happening is that fvwm grabs the keyboard, and if I don't set the xdotool sleep, it executes xdotool and releases the keyboard grab when xdotool has already done is job and so there is no one to receive the fake keystrokes. It is still a bit slugghish though, and it does not support keeping the key pressed (the key press is not repeated).

But why is such a long sleep needed? What could fvwm possibly be doing during that time? Or is xdotool not meant to be used in this context?

**Comment by ainar-g** [comment]
@jordansissel I seem to have had a similar problem, only my shortcut was `Alt+c` and I needed to execute `Ctrl+v`. What I did was:

    xdotool keyup Alt+c
    xdotool key Ctrl+v

Seems to work well.

**Comment by otizonaizit** [comment]
@ainar-g thank you! That fixed me for me too. The previous fix I was using (inserting a short sleep) was working but not reliably. Your fix is working much better, and without the delay I was experiencing with the sleep. Thanks!

**Comment by DiagonalArg** [comment]
@ainar-g - Are you saying you bound Alt+c to `xdotool keyup Alt+c && xdotool key Ctl+v`?

If that's it, then does it leave things in a weird state when you finally release the Alt+c?  Would you want a `xdotool keydown Alt+c` in addition?

**Comment by thebritons** [comment]
> @ainar-g - Are you saying you bound Alt+c to `xdotool keyup Alt+c && xdotool key Ctl+v`?
> 
> If that's it, then does it leave things in a weird state when you finally release the Alt+c? Would you want a `xdotool keydown Alt+c` in addition?
That solution worked for me as well for my purposes (lack of function keys)
`xdotool keyup Ctrl+Up && xdotool key F9`

**Comment by AlirezaJalali** [comment]
I'm using xdotool with libinput-gestures on manjaro, it looks like this
`gesture swipe up 3 xdotool key super+shift+w`
`gesture swipe down 3 xdotool sleep 0.100 key super+shift+s`
`gesture swipe left 3 xdotool sleep 0.100 key --clearmodifiers super+shift+a`
using any of these commands in the command-line works as expected, and libinput-gestures is getting the gestures right as I tested it in verbose.

**Comment by schieni** [comment]
> xdotool **sleep 0.100** key --clearmodifiers End

...and it work for me too! After hours of fighting (unfocused windows works, but focused does not), I find your solution (sleep). Thank you so much!

**Comment by mateja176** [comment]
For CentOS 8, neither approach works, be it relying on `sleep 0.100` or `keyup`.

**Comment by arminstraub** [comment]
Just in case this might be useful to anyone who wants to configure shortcuts:
`xdotool keyup Alt+c && xdotool key Ctl+v` did work for me in a similar situation (KDE global shortcuts on Ubuntu 18.04) but in the end I found that `xvkbd -xsendevent -text "\\Cv"` worked just as well (without the need for a hard-coded keyup).

**Comment by codeswhite** [comment]
I managed to find a good solution for my problem:
Brightness keys `[Fn+F11] -> XF86MonBrightnessDown` not getting recieved (tried all solutions including kernel parameters and udev magic but no luck getting them keys to work btw on windows they do work)

So I mapped (in XFCE keyboard shortcuts settings):
`[Shift+F11] -> xdotool keyup Shift+F11 key --clearmodifiers XF86MonBrightnessDown`
As advised here and it worked, kinda, Ive noticed that im unable to repeatedly press `[Shift+F11]+[F11]+[F11]+...` mutiple times without releasing the Shift key, seems that the Shift key was being released by `keyup` and wasnt getting pressed down until i physically done that.
So the solution for that is releasing only the F11 key and keeping the modifier down:
`[Shift+F11] xdotool keyup F11 key --clearmodifiers XF86MonBrightnessDown`
Hope it help someone who has encountered a similar issue :)

**Comment by ScarletMcLearn** [comment]
xdotool sleep 0.100 keydown Alt sleep 0.100 click 4 sleep 0.100 keyup Alt

Not working on Linux Mint XFCE.

**Comment by phil294** [comment]
can we reopen this? It is not fixed yet (perhaps it isn't even fixable). The proper workaround, as mentioned above, is to do a `keyup the-shortcut-key` before the actual typing.

Problem also discussed recently [here](https://github.com/jordansissel/xdotool/pull/406#issuecomment-1280013095).

**Comment by cassava** [comment]
For i3wm, using `bindsym --release` was the key to fixing my particular similar issue.

**Comment by jasonstone20** [comment]
xdotool sleep 0.100 keydown Alt sleep 0.100 keydown 2 sleep 0.100 keyup Alt sleep 0.100 keyup 2
works for me, using Linux MINT

**Comment by phil294** [comment]
I have found that this is solvable from an application author's point of view (xdotool source or any other tool using `libxdo.so`) by doing a Grab and Ungrab first. So in my app, instead of

```crystal
x_do.keys_raw([key_map], pressed: pressed, delay: 0)
```
I now always do
```crystal
libx_do.keys_raw([key_map], pressed: pressed, delay: 0)
```
X11.display.grab_keyboard(root_win, owner_events: true, pointer_mode: X11::GrabModeAsync, keyboard_mode: X11::GrabModeAsync, time: X11::CurrentTime)
X11.display.ungrab_keyboard(time: X11::CurrentTime)
libx_do.keys_raw([key_map], pressed: pressed, delay: 0)
```
...in other languages accordingly. Instead of grab/ungrab, I also used to send the triggering key UP event like written by folks above, but this breaks X11 key remapping functionality that I'm trying to develop right now

I'll try this out an extended time now, but it seems like this is reliable and might be worth considering to add to libxdo directly?

**Comment by ctrl-alt-g** [comment]
using xvkbd instead of xdotool seems to be the best option on linux mint cinnamon
