### ISSUE TITLE
Xdotool presses key globally

### ISSUE THREAD

**Issue by tuberry** [jordansissel/xdotool#278]
I want to search the text of clipboard in Gnome Shell's overview. Normally I press `Super` and `Ctrl+v` and that works.  But with `xdotool key super ctrl+v`, the keystroke seems to limited in the terminal. How can I let it work 'globally' or how I achieve that? Thanks!

**Comment by hhirsch** [comment]
@tuberry Why is this closed? Have you found a solution? xdotool key "Super_L+4" > /dev/null only prints a 4 instead of changing to desktop number 4 as I expected.

**Comment by tuberry** [comment]
`xdotool key super sleep 0.2 key ctrl+v` did that for me, and `xdotool key super+a` shows applications in gnome shell. So I think you should open another issue for your situation.

**Comment by hhirsch** [comment]
The way I fixed it for me instead of sending the key combination to the WM which does not work I now send the event to change desktops which does work. @tuberry Thank you for your reply.
