### ISSUE TITLE
Any way to get it work on Wayland?

### ISSUE THREAD

**Issue by qnxdev** [jordansissel/xdotool#282]
xdotool windowminimize <id> does nothing..

**Comment by jordansissel** [comment]
Unfortunately wayland is incompatible in almost every way with xdotool.
Even attempting to write a similar tool for Wayland may not be possible
because similar capabilities do not exist in Wayland or its ecosystem :(

**Comment by qnxdev** [comment]
So is there anyway to get custom gestures working on linux with wayland today?

**Comment by jordansissel** [comment]
I'm not sure. I've avoided Wayland for several reasons, one of which
includes missing tools similar to xdotool. If you end up finding something
useful for your needs, posting any findings on this issue may help others
in the future who are also using Wayland.

**Comment by stjornandi** [comment]
I dont know why, but it seems that I am using Wayland and that xdotool works....

**Comment by markstos** [comment]
@stjornandi Could be that you are running XWayland, so xdotool is communicating with an X11 server running under Wayland and not Wayland itself?

**Comment by stjornandi** [comment]
Yes, it only works with some applications. Probably those are running on XWayland.

**Comment by madscientist42** [comment]
Bingo.

**Comment by markstos** [comment]
To type into apps on Wayland, there is the `wtype` project.

**Comment by aixiangfei** [comment]
This project may help you!

https://github.com/ReimuNotMoe/ydotool

**Comment by JohnGebbie** [comment]
You might like [dotool](https://git.sr.ht/~geb/dotool) which works everywhere but only does the keyboard and mouse side of things.

**Comment by jordansissel** [comment]
> “ This screams for three seconds:”

the readme gave me a good chuckle. Nice work!

Im open to having a link to dotool in the xdotool readme to help folks who are on Wayland or other non-x11 systems :)

**Comment by JohnGebbie** [comment]
Oh wow thank you! That'd be really nice :)
