### ISSUE TITLE
xdo_get_active_modifiers disrupts the conventions of the library

### ISSUE THREAD

**Issue by KoFish** [jordansissel/xdotool#3]
`xdo_get_active_modifiers()` returns a pointer to a struct instead of returning the values in arguments like all similar functions in the library does.
By changing this there would be no need for the `xdo_active_mods_t` struct either.

**Comment by jordansissel** [comment]
The current method definition is this:

`  int xdo_get_active_modifiers(const xdo_t *xdo, charcodemap_t **keys, int *nkeys) {`

I think 7cf1eaaf fixed this.

**Comment by jordansissel** [comment]
Closing since I think this was resolved in 7cf1eaaf; reopen if you feel otherwise :)
