### ISSUE TITLE
unable to properly output 'key' command to focused program when ran from hotkey daemon

### ISSUE THREAD

**Issue by BombchuLink** [jordansissel/xdotool#304]
title is fairly straightforward.

obviously running `xdotools key Aacute` prints out á in the terminal, but running it inside of the sxhkd daemon does not make the key properly press inside of the highlighted window.

I am unsure if this is an xdotool issue, or a sxhkd issue, but I thought submitting issues to both would be helpful

**Comment by jordansissel** [comment]
Thanks for filing!

How is the daemon running?

I have an idea why it isn’t working: X11 window system uses an environment
variable to figure out which display to connect to. It’s not as common
today, but X11/Xorg can run multiple window servers on the same computer.
Most commonly, folks run just one.

The environment variable is “DISPLAY” and in your terminal, when you run
xdotool manually, you could see this value by running:

echo $DISPLAY

If you set this environment variable in your daemon to the same value,
typically “:0” then I think xdotool should work.

Let me know if this helps :)

**Comment by SeerLite** [comment]
Hi!
I don't think it has to do with `DISPLAY`, since `sxhkd` itself also runs inside xorg and exports `DISPLAY` to all programs that run from it.
I'm pretty sure this actually has to do with `sxhkd` grabbing the keyboard input when running the keybind.
The workaround to this is to:
* Run the command when the keybind is _released_. (`@`)
* Ask `xdotool` to clear the modifiers so the modifier of the keybind isn't active when pressing key.

So, using the your example:
```sxhkd
hyper + a
    xdotool key Aacute
```
you'd have to modify it like this:
```sxhkd
@hyper + a 
    xdotool key --clearmodifiers Aacute
```

Let me know if that works!

**Comment by jordansissel** [comment]
Ahh great point!

If the above suggestions doesn’t work, a common workaround is to sleep
briefly to give your fingers time to release the keys and give the program
(sxhkd) time to release the key grab.

**Comment by BombchuLink** [comment]
Sadly, the above example doesn't seem to be working with mapping the bind on release, as SeerLight Intended. 

I'm unsure how to actually get sleeping to work as jorsanissel suggested, since It's sxhkd that's mis-grabbing the input to being with.

**Comment by SeerLite** [comment]
I wonder why it doesn't work. I tested it with `@shift + p` and `@super + Right` and it seemed to work fine.
Do you get anything in the output of `sxhkd`? You can check by killing the running it in a terminal after killing the one you'd start with bspwm.

Also, the following is how it'd look by sleeping before running `xdotool`. It worked fine for me too.
```sxhkdrc
hyper + a
    sleep 0.1; xdotool key --clearmodifiers Aacute
```

I gotta say though, if you're doing this to remap keys that you don't have on your keyboard/layout, the `sxhkd` + `xdotool` combo isn't the _best_ for this task. It has the overhead of calling 2 processes each time you want to press the keys and you gotta deal with this key-grabbing thing, so it doesn't look smooth.

I needed something similar once too, and decided to just use `xkbcomp` to directly remap the keys processed by the X server. [The ArchWiki has an entire wiki page about this process](https://wiki.archlinux.org/index.php/X_keyboard_extension).
It took me a few tries though, it wasn't easy. Just throwing it out there in case you think it might be worth it in the end (note that `sxhkd` + `xdotool` can still do the job and it is simpler to set up) :p

**Comment by BombchuLink** [comment]
Ok it's now working on my end with the sleep 0.1!  [^]-[^]

The key remap thing is, for all intentions, going to remap single keycodes to key combinations, such as `j` to ``Down+Alt_L`` (just tested it and it WORKS)

There IS an issue where I am getting Á instead of á (with or without --clearmodifiers), and I'm unsure why? (Now that I think about it, I might have something going on from configuring and reconfiguring, and re-reconfiguring stuff without rebooting) But if it's fine on your end I'm probably good? ('ll follow up with a verification that this issue is only on my end after I post this, this is actually the last part of the post I'm writing lol)

To answer you question about xkbcomp; if it wasn't key combinations I was re-mapping to, I would just use xmodmap to set the keycodes how I want (actually I already do a lot of remapping to make things more ergonomical such as having {} [] and () close to the home row with Mode_switch mapped to the spacebar (unless space is pressed on it's own then it's space thanks to xcape))

I'm working on setting up system wide keyboard modularity, and depending on what window is focused, it loads a different sxhkd config, and different xmodmap keycode file (if nessisary) to allow programs that don't have custom keyboard short-cuts (looking at you discord), have custom keyboard shortcuts. Obviously it would have to be toggle-able (very similar to how vim uses modes) and this was the last piece of the puzzle!

I'm sure I could get something out of xkbcomp, if I was to learn about it and get a proper like config going, but for now I think I have my issue solved enough to get everything together. I will keep that in mind when diving back into this though.

Now I just have to finish the scripts and key remapping, make a youtube video showing the world, and get everyone to use modularity or something. I'm just ranbling at this point, sorry lol.

Again, thanks again a TON SeerLite (and you too jordan) for your assistance!!

**Comment by jordansissel** [comment]
Hurray! I’m glad you were able to find a path forward :)

**Comment by BombchuLink** [comment]
I found out the "issue"
á = aacute
Á = Aacute 
My tired self just didn't realise that there was a differentiation. Either way, all is good now so I'll close the issue.
