### ISSUE TITLE
How to chain exec

### ISSUE THREAD

**Issue by aacebedo** [jordansissel/xdotool#315]
Hi

I want  to start an app in the hidden state without having the window to appear at all.

To do so I plan to use the exec command chained with a windowunmap command.

If I put the windowunmap command before the exec, it is applied to the terminal window running the command.

If I put the windowunmap after it is taken as an argument of the app I start and thus not applied.

How could I do that ?

Example:
```bash
$> xdotool exec gedit getactivewindow windowunmap
vs

$> xdotool getactivewindow windowunmap exec gedit
```

**Comment by Ingvix** [comment]
Might not be relevant to you anymore but for anyone else ending up here trying to find a solution for this:

I learned from #280, whose description seemed somewhat ambiguous to me, that exec has undocumented options `--args N` and `--terminator TERM` to determine where the command ends and another one begins.

**Comment by aacebedo** [comment]
I close the issue since I moved on wayland since.
