### ISSUE TITLE
Please update the readme

### ISSUE THREAD

**Issue by robkam** [jordansissel/xdotool#337]
This should be in the readme, to stop people wasting their time trying to get this otherwise fine program to work in Wayland:
"Unfortunately Wayland is incompatible in almost every way with xdotool. Even attempting to write a similar tool for Wayland may not be possible because similar capabilities do not exist in Wayland or its ecosystem :("

**Comment by jordansissel** [comment]
#342 will now cause an error when xdotool is run on XWayland. Hopefully this will help reduce the amount of surprises folks get when running xdotool for the first time or, like me today, being surprised by my linux distro upgrade switching automatically to Wayland.

**Comment by jordansissel** [comment]
#343 updates the readme with a warning about Wayland.
