### ISSUE TITLE
"mousemove" to the same position jams read operation

### ISSUE THREAD

**Issue by MXarko** [jordansissel/xdotool#463]
If xdotool in a loop containing a "read" operation execute "mousemove" to the position the mouse already is, that will jam the "read" operation so it will need some time to unjam, during which subsequent inputs will not be processed properly. I attached an example program.
[xdttest.txt](https://github.com/user-attachments/files/15916463/xdttest.txt)

**Comment by jordansissel** [comment]
This looks like a bug in the `--sync` flag for `mousemove` -

This will also hang on the 2nd invocation:

```
# This works
% xdotool mousemove --sync 5 5

# This hangs (unless the mouse moves)
% xdotool mousemove --sync 5 5
```

This happens because xdotool doesn't (but should!) check if the mouse is already at the given location and, if so, shouldn't wait.

I opened #464 with a fix.

**Comment by jordansissel** [comment]
I hope the pull request fixes it, but if it does not, please let me know.
