### ISSUE TITLE
xdotool key enter

### ISSUE THREAD

**Issue by sosohu** [jordansissel/xdotool#57]
Hi, I want to run a command `xdotool key enter`, but I get error like this: 

`(symbol) No such key name 'enter'. Ignoring it.`

So. I would like to know whether there is an "enter" key?

**Comment by jordansissel** [comment]
I think it's `Return`, try `xdotool key Return`

**Comment by herr-biber** [comment]
I successfully used `xdotool key KP_Enter`

**Comment by sosohu** [comment]
@herr-biber  Yeah, it does work, thank you for your answer

**Comment by roddik** [comment]
`Return` is the correct answer, `KP_Enter` is the numpad enter

**Comment by gamer01** [comment]
Is there anywhere a full reference for that?

**Comment by jerkey** [comment]
Is this documented anywhere?  I found this answer similarly by searching for KP_Enter and this is the only result :(

**Comment by jordansissel** [comment]
I don’t have it documented. It’s listed in a X11 header file keysymdefs.h

I’d welcome anyone transforming that into a document for this project :)

**Comment by gamer01** [comment]
https://www.cl.cam.ac.uk/~mgk25/ucs/keysymdef.h Thats already a good start!

**Comment by Purple-tulip** [comment]
You can use `xev`
>  https://www.reddit.com/r/commandline/comments/2xrel2/xdotool_how_do_i_send_a_plus_sign_key_event/

**Comment by pakair** [comment]
```
KP_Enter works but Return does not.

1. xdotool type uptime; xdotool key KP_Enter     works
2. xdotool type uptime; xdotool key Return       does not
```
