### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by dkasak** [jordansissel/xdotool#62]
If I'm not missing something, the last released version (xdotool-2.20110530.1) is ancient (from 2011). Is a new release planned and what's stopping it?

**Comment by jordansissel** [comment]
What does a release mean to you? Knowing this would help me answer your question. :)

**Comment by dkasak** [comment]
I guess replacing the tarball in the download section [here](http://www.semicomplete.com/projects/xdotool/) with one containing the codebase as it was in one of the more recent commits so my distro would pick it up. :P Specifically, something after the so bump of libxdo.

**Comment by jordansissel** [comment]
I need to find a new location to host releases with googlecode being destroyed soon.

**Comment by jordansissel** [comment]
(I have hosting, it's just the energy of setting things up and migrating old releases)

**Comment by PlasmaPower** [comment]
Any reason Github releases won't work?

**Comment by jordansissel** [comment]
@PlasmaPower I was certain that Github deleted that feature years ago, but it looks like it's back now - cool. I'll consider that.

**Comment by jordansissel** [comment]
https://github.com/jordansissel/xdotool/releases/tag/v3.20150503.1
