### ISSUE TITLE
Not moving mouse cursor when under some conditions

### ISSUE THREAD

**Issue by tomoki** [jordansissel/xdotool#64]
I found that xdotool doesn't move mouse cursor under following conditions.

1. Move cursor to (100,200).
   $ xdotool mousemove 100 200

2. Move cursor using --window option and specify __same location as step 1__
   $ xdotool mousemove --window some_window 100 200

3. Mouse should move to (some_window.x + 100,some_window.y + 200). But cursor remains at (100,200).

It is because following if statement in _mousemove function in cmd_mousemove.c.

```
  /* Break early if we don't need to move */
  if (mx == x && my == y && mscreen == screen) {
    return 0;
  }
```

Adding ```window == CURRENTWINDOW``` condition is not enough.
To quick fix, we can remove "Break early if we don't need to move" conditions.

Any better solutions?

**Comment by tomoki** [comment]
Any update on this issue?
If my description is not enough, I want to add more information.

**Comment by tomoki** [comment]
I made testcase for this issue in my fork.
https://github.com/tomoki/xdotool/blob/test_mousemove_same_position_of_the_other_window/t/test_mousemove.rb

```ruby
  # https://github.com/jordansissel/xdotool/issues/64
  def test_mousemove_same_position_of_the_other_window
    move_x = 100
    move_y = 200

    # It seems window wid located at (0, 0) at first.
    xdotool_ok "windowmove --sync #{@wid} 400 400"

    status, xwininfo_output = runcmd "xwininfo -id #{@wid}"
    the_other_window_x = xwininfo_output.grep(/ Absolute upper-left X:/).first[/[0-9]+/].to_i
    the_other_window_y = xwininfo_output.grep(/ Absolute upper-left Y:/).first[/[0-9]+/].to_i

    xdotool_ok "mousemove --sync #{move_x} #{move_y}"
    xdotool_ok "mousemove --sync --window #{@wid} #{move_x} #{move_y}"

    assert_mouse_position_near(the_other_window_x + move_x,
                               the_other_window_y + move_y)
  end
```

**Comment by jordansissel** [comment]
I agree with your solution. Thank you :)

**Comment by tomoki** [comment]
Thank you for your merging my fork.
